# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "attachments", :force => true do |t|
    t.column "entry_id",     :integer, :null => false
    t.column "content_type", :string
    t.column "filename",     :string,  :null => false
    t.column "size",         :integer, :null => false
    t.column "type",         :string
    t.column "metadata",     :string
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
    t.column "width",        :integer
    t.column "height",       :integer
  end

  add_index "attachments", ["parent_id"], :name => "index_attachments_on_parent_id"
  add_index "attachments", ["entry_id"], :name => "index_attachments_on_entry_id"

  create_table "avatars", :force => true do |t|
    t.column "user_id",      :integer, :null => false
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "size",         :integer
    t.column "position",     :integer
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
    t.column "width",        :integer
    t.column "height",       :integer
  end

  add_index "avatars", ["parent_id"], :name => "index_avatars_on_parent_id"
  add_index "avatars", ["user_id"], :name => "index_avatars_on_user_id"

  create_table "comments", :force => true do |t|
    t.column "entry_id",     :integer,                     :null => false
    t.column "comment",      :text
    t.column "user_id",      :integer,  :default => 0
    t.column "ext_username", :string
    t.column "ext_url",      :string
    t.column "is_disabled",  :boolean,  :default => false, :null => false
    t.column "created_at",   :datetime,                    :null => false
  end

  add_index "comments", ["entry_id", "user_id"], :name => "index_comments_on_entry_id_and_user_id"

  create_table "entries", :force => true do |t|
    t.column "user_id",     :integer,                     :null => false
    t.column "data_part_1", :text
    t.column "data_part_2", :text
    t.column "data_part_3", :text
    t.column "type",        :string,                      :null => false
    t.column "is_disabled", :boolean,  :default => false, :null => false
    t.column "created_at",  :datetime,                    :null => false
    t.column "modified_at", :datetime
  end

  add_index "entries", ["user_id", "created_at", "type"], :name => "index_entries_on_user_id_and_created_at_and_type"

  create_table "user_friends", :force => true do |t|
    t.column "user_id",   :integer, :null => false
    t.column "friend_id", :integer, :null => false
  end

  create_table "users", :force => true do |t|
    t.column "email",        :string
    t.column "is_confirmed", :boolean,  :default => false, :null => false
    t.column "password",     :string
    t.column "openid",       :string
    t.column "url",          :string,                      :null => false
    t.column "settings",     :text
    t.column "is_disabled",  :boolean,  :default => false, :null => false
    t.column "created_at",   :datetime,                    :null => false
    t.column "modified_at",  :datetime
  end

  add_index "users", ["url"], :name => "index_users_on_url"
  add_index "users", ["openid"], :name => "index_users_on_openid"
  add_index "users", ["email"], :name => "index_users_on_email"

end
